### ISSUE TITLE
运行 java -jar a.jar  后 ， 直接报错

### ISSUE THREAD

**Issue by dogscar** [shuaigeadou/avHelper#1]
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
        at org.aver.avHelper.Config.readConfig(Config.java:71)
        at org.aver.avHelper.AvHelper.main(AvHelper.java:34)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)

**Comment by shuaigeadou** [comment]
不应该呀，jar包都在里面呢
